apiVersion: v1
kind: Service
metadata:
  name: "service-helloweb"
spec:
  selector:
    app: helloweb
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31200